---
version: 2
jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -qq make
      - run: make flake8
  buildrpm:
    machine: true
    steps:
      - checkout
      - run: make dom0-rpm
  launcher-tests-buster:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run:
          name: Install dependencies and run Python tests for launcher
          command: |
            cd launcher/
            set -e
            virtualenv .venv
            source .venv/bin/activate
            pip install --require-hashes -r test-requirements.txt
            make test && make bandit && make black

workflows:
  version: 2
  securedrop_workstation_ci:
    jobs:
      - lint
      - buildrpm
      - launcher-tests-buster
