---
version: 2
jobs:
  lint:
    docker:
      - image: debian:bullseye
    steps:
      - run: apt-get update && apt-get install -y sudo git make
      - checkout
      - run:
          name: Install dependencies and run linters
          command: |
            make install-deps
            python3 -m venv .venv
            source .venv/bin/activate
            pip install --require-hashes -r dev-requirements.txt
            sudo apt-get install -y file
            make black
  buildrpm:
    docker:
      - image: debian:bullseye
    steps:
      - run: apt-get update && apt-get install -y sudo git make
      - checkout
      - run: make install-deps
      - run: make dom0-rpm
  reprotest:
    docker:
      - image: debian:bullseye
    steps:
      - run: apt-get update && apt-get install -y sudo git make
      - checkout
      - run: make install-deps
      # Patch reprotest in-place to skip 'setarch' prefix, which fails under containers.
      # See for more info in https://github.com/freedomofpress/securedrop-debian-packaging/pull/213/commits/18770bd44ec54da86f436515da4452c05111605e
      # We should probably try to upstream this as an option.
      - run:
          command:
            sudo sed -i -re "292s/^(\s+).*\$/\1return _.prepend_to_build_command_raw('')/" /usr/lib/python3/dist-packages/reprotest/build.py
      - run: make reprotest-ci
  launcher-tests:
    docker:
      - image: debian:bullseye
    steps:
      - run: apt-get update && apt-get install -y sudo git make
      - checkout
      - run:
          name: Install Python requirements and run tests for launcher
          command: |
            make install-deps
            sudo apt-get install -y python3-pyqt5
            cd launcher/
            make venv && source .venv/bin/activate
            make check

workflows:
  version: 2
  securedrop_workstation_ci:
    jobs:
      - lint
      - buildrpm
      - reprotest
      - launcher-tests
